substitutions:
  device_name: bee-hive-monitor
  friendly_name: "Bee Hive Monitor"
  
esphome:
  name: bee-hive-monitor
  friendly_name: Bee Hive Monitor

esp32:
  board: seeed_xiao_esp32s3
  framework:
    type: arduino
  variant: esp32s3

psram:
  mode: octal
  speed: 80MHz

i2c:
  - id: bus_a
    sda: GPIO40
    scl: GPIO39
    scan: true
    frequency: 400kHz

logger:
  level: INFO

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  # Recommended: Use static IP for reliability
  manual_ip:
    static_ip: 192.168.1.100  # CHANGE THIS to match your network
    gateway: 192.168.1.1      # CHANGE THIS to your router IP
    subnet: 255.255.255.0
  
  ap:
    ssid: "Bee Hive Monitor Fallback"
    password: !secret fallback_password

captive_portal:

web_server:
  port: 80

# Camera Configuration
esp32_camera:
  name: "Camera"
  external_clock:
    pin: GPIO10
    frequency: 20MHz
  i2c_id: bus_a
  data_pins: [GPIO15, GPIO17, GPIO18, GPIO16, GPIO14, GPIO12, GPIO11, GPIO48]
  vsync_pin: GPIO38
  href_pin: GPIO47
  pixel_clock_pin: GPIO13
  
  resolution: 1600x1200
  jpeg_quality: 10
  max_framerate: 5 fps
  idle_framerate: 0.2 fps
  
  # Adjust based on your camera orientation
  vertical_flip: false
  horizontal_mirror: false
  
  # Camera adjustments (optional)
  contrast: 0
  brightness: 0
  saturation: 0

# Sensors
sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
    
  - platform: uptime
    name: "Uptime"

binary_sensor:
  - platform: status
    name: "Status"

button:
  - platform: restart
    name: "Restart"

switch:
  - platform: template
    name: "Monitoring Enabled"
    id: monitoring_enabled
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
